### ISSUE TITLE
Use/Code License

### ISSUE THREAD

**Issue by gordonmcshane** [burkeholland/InstaSharp#13]
Would you mind adding a license, preferably a permissive one? I would love to use this in a project, but would need something like MS-PL or MIT or similarly compatible.

**Comment by felipepessoto** [comment]
I agree, but I want the @burkeholland opinion before take action

**Comment by burkeholland** [comment]
Approved. Go with the most permissive. That might be Apache V2.

**Comment by gordonmcshane** [comment]
Excellent!
