### ISSUE TITLE
Media ID How to get it? Please help

### ISSUE THREAD

**Issue by RayedM** [burkeholland/InstaSharp#14]
Dear all,

I want to post comment. It requires "Media ID".

How I can obtain Media ID? Does it have to be recent one.

I tried the following code but it give me null object can you help

My code
//config and info are correct
InstaSharp.Endpoints.Users.Authenticated u = new InstaSharp.Endpoints.Users.Authenticated(config, info);
        InstaSharp.Endpoints.Comments.Authenticated c = new InstaSharp.Endpoints.Comments.Authenticated(config, info);

```
    InstaSharp.Model.Responses.MediasResponse res = u.Recent();

    string nextMaxId = res.Pagination.NextMaxId;


    c.Post(nextMaxId, "hello world");
```

////////////////////////////////////////////
Thank you

**Comment by felipepessoto** [comment]
First, you need a special permission from Instagram to post comments.

To get Id, use the Id property: u.Recent().First().Id
