### ISSUE TITLE
A first chance exception of type 'System.Net.Http.HttpRequestException' occurred in System.Net.Http.dll

### ISSUE THREAD

**Issue by YannickG1** [burkeholland/InstaSharp#21]
Hi, I'm currently doing a school project and when trying to get data from the newest library from fujiy, I'm always getting the error stated in the title at the call from a method of the library. We have to learn c# all by ourselves, including workin with visual studio so sorry if this is a beginners mistake. I included the instasharp project in my solution and made a reference to it in my main project ofcouse.I tried google first but it didn't really help out.. I hope you can point me in the right direction, here's the code:

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using InstaSharp;
using InstaSharp.Endpoints;
using InstaSharp.Models.Responses;
using Newtonsoft.Json;
using System.Net.Http;

namespace instagram_test
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

```
        string clientId = "-------------";
        string clientSecret = "------------------------";
        string redirectUri = "http://www.groept.be"; // Any URL 
        const string oAuthUri = "https://api.instagram.com/oauth";
        const string apiUri = "https://api.instagram.com/v1";
        const string realtimeUri = "https://api.instagram.com/v1/subscriptions/";

        var config = new InstaSharp.InstagramConfig(clientId,
            clientSecret, redirectUri,
            redirectUri,apiUri,oAuthUri,realtimeUri);

        Search(config);

        // listBox1.Items.Add("Yoo de data wordt binnegehaald");

    }

    public async Task Search(InstaSharp.InstagramConfig config)
    {
        var media = await new InstaSharp.Endpoints.Media(config).Search(50.879535, 4.699953, DateTime.Now.AddDays(-7),DateTime.Now.AddDays(-6), 5000);
```

listBox1.Items.Add(media.Data.Count);
            for (int i = 0; i < media.Data.Count; i++)
            {
                listBox1.Items.Add(media.Data.ElementAt(i).Id);
            }
        }

Thanks in advance

**Comment by felipepessoto** [comment]
@YannickG1 I dunno if it is the problem, but try to call Search in Load event, since contructor can´t be async:

```
public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();
    }

    public async void Form1_Load(){

        string clientId = "-------------";
        string clientSecret = "------------------------";
        string redirectUri = "http://www.groept.be"; // Any URL 
        const string oAuthUri = "https://api.instagram.com/oauth";
        const string apiUri = "https://api.instagram.com/v1";
        const string realtimeUri = "https://api.instagram.com/v1/subscriptions/";

        var config = new InstaSharp.InstagramConfig(clientId,
            clientSecret, redirectUri,
            redirectUri,apiUri,oAuthUri,realtimeUri);

        await Search(config);

        // listBox1.Items.Add("Yoo de data wordt binnegehaald");

}

public async Task Search(InstaSharp.InstagramConfig config)
{
    var media = await new InstaSharp.Endpoints.Media(config).Search(50.879535, 4.699953, DateTime.Now.AddDays(-7),DateTime.Now.AddDays(-6), 5000);
    listBox1.Items.Add(media.Data.Count);
    for (int i = 0; i < media.Data.Count; i++)
    {
        listBox1.Items.Add(media.Data.ElementAt(i).Id);
    }
}
```

**Comment by YannickG1** [comment]
I tried your solution but no luck.. it gives the same error, but now another one too:

A first chance exception of type 'System.Net.Http.HttpRequestException' occurred in System.Net.Http.dll
A first chance exception of type 'System.Net.Http.HttpRequestException' occurred in mscorlib.dll
A first chance exception of type 'System.Net.Http.HttpRequestException' occurred in mscorlib.dll
A first chance exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll

all happens right on the method: await new Media(config).Search(50.879535, 4.699953, DateTime.Now.AddDays(-7), DateTime.Now.AddDays(-6), 5000);

**Comment by felipepessoto** [comment]
Would you send me the project?

Em quinta-feira, 10 de outubro de 2013, YannickG1 escreveu:

> I tried your solution but no luck.. it does fix the error though! It's
> just that nothing happens... I also get a "The thread '' (0x6c8) has exited
> with code 0 (0x0)." like a few seconds after I launch the project and then
> nothing..
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/burkeholland/InstaSharp/issues/21#issuecomment-26036488
> .

## 

Felipe Fujiy Pessoto - felipepessoto@gmail.com
http://blog.fujiy.net

**Comment by YannickG1** [comment]
Ok I will send it to your hotmail

**Comment by YannickG1** [comment]
Problem solved by fujiy! Needed to add slashes to the end of the uri's !
