### ISSUE TITLE
Nullreference when trying to access image.standardresolution

### ISSUE THREAD

**Issue by YannickG1** [burkeholland/InstaSharp#23]
Hi,

I'm using your library for a school project and everything works fine except 1 function to get the url for the images. Every time I try to call the media.images.standardresolution.url (or lowresolution or thumbnail) I get a nullreference. Ay idea why this is happening? I checked the json from the instagram api manually and it is still publishing the resolution urls so that is not the problem. For some reason your libraray isn't deserialising them anymore I think.

**Comment by felipepessoto** [comment]
I fixed it, I just forgot to send the pull request. I will do it today night

**Comment by YannickG1** [comment]
Ok thanks!

**Comment by felipepessoto** [comment]
Done

**Comment by felipepessoto** [comment]
Done

2013/11/7 YannickG1 notifications@github.com

> Ok thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/burkeholland/InstaSharp/issues/23#issuecomment-27949799
> .

## 

Felipe Fujiy Pessoto - felipepessoto@gmail.com
http://blog.fujiy.net
