### ISSUE TITLE
media.Search not working

### ISSUE THREAD

**Issue by jpugarte1** [burkeholland/InstaSharp#25]
var mediaSearchResults = media.Search(42.3736, -71.1106, minTimeStamp, maxTimeStamp, searchRadius);

The previous assignment throws the following error:

An unhandled exception of type 'System.UriFormatException' occurred in System.dll
Additional information: Invalid URI: The URI scheme is not valid.

I might be wrong, but it seems to me that the media.Search method is creating a wrong URI. I've been browsing the source files but I haven't been able to find what's causing the problem. Any ideas?

**Comment by felipepessoto** [comment]
How did you create media instance?

Em sábado, 9 de novembro de 2013, jpugarte1 escreveu:

> var mediaSearchResults = media.Search(42.3736, -71.1106, minTimeStamp,
> maxTimeStamp, searchRadius);
> 
> The previous assignment throws the following error:
> 
> An unhandled exception of type 'System.UriFormatException' occurred in
> System.dll
> Additional information: Invalid URI: The URI scheme is not valid.
> 
> I might be wrong, but it seems to me that the media.Search method is
> creating a wrong URI. I've been browsing the source files but I haven't
> been able to find what's causing the problem. Any ideas?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/burkeholland/InstaSharp/issues/25
> .

## 

Felipe Fujiy Pessoto - felipepessoto@gmail.com
http://blog.fujiy.net

**Comment by jpugarte1** [comment]
Hi fujiy. This is my code (at this point I'm already authenticated and other querys are working perfectly):

 private void SearchRecentMedia_Click(object sender, EventArgs e)
        {
            DateTime minTimeStamp = DateTime.Now.AddDays(-3);
            DateTime maxTimeStamp = DateTime.Now.AddDays(-1);
            int searchRadius = 5000;
            var media = new InstaSharp.Endpoints.Media.Authenticated(config, ainfo);

```
        var mediaSearchResults = media.Search(42.3736, -71.1106, minTimeStamp, maxTimeStamp, searchRadius); /
        this.richTextBox1.AppendText(mediaSearchResults.Json);
  }
```

**Comment by felipepessoto** [comment]
@jpugarte1 try using v2 https://www.nuget.org/packages/InstaSharp/2.0.0-beta2

**Comment by jpugarte1** [comment]
Hi @fujiy ,

Thanks for your help. I tried v2 but now a lot of stuff doesn't work anymore.I am completely new in c# and this is a School Project. I don't think I could modify my entire project now to make it work with v2.0 (or could I? Since I'm so noob I don't really know what I would need to change to migrate my code from v1.1 to v2.0). Anyway, do you think I could just stay on 1.1 and modify your library trying to fix whatever is causing the Media.Search error?

**Comment by felipepessoto** [comment]
I will try, but I never used that version

**Comment by jpugarte1** [comment]
Hi fujiy,

I´ve been trying InstaSharp 2.0 beta and I'm having trouble authenticating. I'm getting an error:

An exception of type 'System.InvalidOperationException' occurred in System.dll but was not handled in user code
Additional information: This operation is not supported for a relative URI.

I think I'm doing things right, specially after verifying what'sinside OAuth.cs. I'm passing the right code (I suppose) and I ran out of ideas. Any suggestions?

This is my code:

string oauthcode = this.textBox1.Text;  (I'm getting a code response from Instagram API)  
OAuth auth = new OAuth(config);  // The config parameters should be fine —clientId, clientSecret, etc  
InstaSharp.Models.Responses.OAuthResponse ainfoTemp = await auth.RequestToken(oauthcode);   <---- Here it breaks  
ainfo = ainfoTemp;

**Comment by felipepessoto** [comment]
@jpugarte, I commit a fix, could you get the new code and try again?
