### ISSUE TITLE
Error in Client App when using Instasharp (from HTTP Portable Library).

### ISSUE THREAD

**Issue by theShiva** [burkeholland/InstaSharp#29]
I am getting the following error when I add a Project reference to the Instasharp source, update all packages, and then try to instantiate the endpoint object using my clientId and clientSecret.

```
Method not found: 'Void System.Net.Http.HttpClientHandler.set_AutomaticDecompression(System.Net.DecompressionMethods)'.
```

I found the cause to be that the following 2 packages had to be added to the Instasharp client project also (the WebApp in my case) in order for the error to be resolved.
1) http://www.nuget.org/packages/Microsoft.Net.Http/
2) http://www.nuget.org/packages/Microsoft.Bcl.Async/

Can you please update the documentation on github and on instasharp.org to reflect this so that other developers can benefit from it.

Thank you

**Comment by felipepessoto** [comment]
Hi Shiva,

If you use the NuGet package it should install all dependencies. Anyway we
need to update the docs. I don't have access to instasharp.org but I can
accept a pull request to update GitHub readme

Thx

Em domingo, 22 de dezembro de 2013, Shiva Manjunath escreveu:

> I am getting the following error when I add a Project reference to the
> Instasharp source, update all packages, and then try to instantiate the
> endpoint object using my clientId and clientSecret.
> 
> ```Method not found: 'Void
> System.Net.Http.HttpClientHandler.set_AutomaticDecompression(System.Net.DecompressionMethods)'.
> 
> I found the cause to be that the following 2 packages had to be added to the Instasharp client project also (the WebApp in my case) in order for the error to be resolved.
> 1) http://www.nuget.org/packages/Microsoft.Net.Http/
> 2) http://www.nuget.org/packages/Microsoft.Bcl.Async/
> 
> Can you please update the documentation on github and on instasharp.org to reflect this so that other developers can benefit from it.
> 
> Thank you
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/burkeholland/InstaSharp/issues/29
> .

## 

Felipe Fujiy Pessoto - felipepessoto@gmail.com
http://blog.fujiy.net

**Comment by theShiva** [comment]
Hi Fujiy,

Correct, the build downloads the Nuget packages and installs all the dependencies. If you build the whole solution, the 1st time I get the errors. Then if I build the instasharp project separately first, and then the solution it goes away. 

I'll update the documentation and submit a pull request to you soon.1st need to send you a pull request for a bug in the `Counts.cs` model :)
