### ISSUE TITLE
Compiled Library Link and Source code link out of Sync on instasharp.org

### ISSUE THREAD

**Issue by theShiva** [burkeholland/InstaSharp#30]
Hi,

The following binary dll ( / instasharp assembly) link on instasharp.org is to a previous version of the source
https://github.com/downloads/burkeholland/InstaSharp/InstaSharp.zip

Whereas the current source code project has been radically revamped. I used the compiled assembly in my WebApp and then found that the User object was not having the Counts object populated. So I downloaded the source project from Github and added it as a project reference to my WebApp that is using Instasharp as client. When I built my project that was previously working with the binary dll (downloaded from the link above), I got all kinds of errors including in the config object etc. 

Please update the links on instasharp.org to sync with the current version. Or update your documentation. Right now, it is very confusing.

**Comment by felipepessoto** [comment]
Hi Shiva,

We need to update the docs. I don't have access to instasharp.org but I can
accept a pull request to update GitHub readme

Thx

Em domingo, 22 de dezembro de 2013, Shiva Manjunath escreveu:

> Hi,
> 
> The following binary dll ( / instasharp assembly) link on instasharp.orgis to a previous version of the source
> https://github.com/downloads/burkeholland/InstaSharp/InstaSharp.zip
> 
> Whereas the current source code project has been radically revamped. I
> used the compiled assembly in my WebApp and then found that the User object
> was not having the Counts object populated. So I downloaded the source
> project from Github and added it as a project reference to my WebApp that
> is using Instasharp as client. When I built my project that was previously
> working with the binary dll (downloaded from the link above), I got all
> kinds of errors including in the config object etc.
> 
> Please update the links on instasharp.org to sync with the current
> version. Or update your documentation. Right now, it is very confusing.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/burkeholland/InstaSharp/issues/30
> .

## 

Felipe Fujiy Pessoto - felipepessoto@gmail.com
http://blog.fujiy.net

**Comment by burkeholland** [comment]
@fujiy If you want to create a gh-pages site (based on the README or otherwise), I'll update the DNS entries for Instasharp.org to point to it.

**Comment by felipepessoto** [comment]
@burkeholland I created the gh-pages based on current README. http://fujiy.github.io/InstaSharp/

@theShiva will try to help us updating the docs.

**Comment by burkeholland** [comment]
Looks great.  Let me know when you are comfortable with the content and
I'll repoint the DNS.
