### ISSUE TITLE
A User's FollowedBy property is always Null.

### ISSUE THREAD

**Issue by theShiva** [burkeholland/InstaSharp#31]
The `FollowedBy` property (indicating how many other IG users are following a `User`) in the `Counts` models that is part of the `User` model is always `Null`.

I found out that this is happening because the `JSON` property name for the number of followers is `followed_by` and not `FollowedBy` so this property in the C# class needs a `JsonProperty` attribute decoration.

**Comment by felipepessoto** [comment]
Done. Thx
