### ISSUE TITLE
Is the head of this project working currently?

### ISSUE THREAD

**Issue by sebastienricher** [burkeholland/InstaSharp#34]
I'm trying to authenticate and there seams to be some issues with it...

**Comment by felipepessoto** [comment]
Could you write some piece of code and what issues you are experiencing?

**Comment by sebastienricher** [comment]
Well, I removed the code for now because I couldn't get it to authenticate. But I'm not familiar with c# async and await. So I'm not sure I understand how to have the "get" action handle this. I catch the callback from Instagram correctly, then I try InstaSharp.OAuth.RequestToken(code)... but my understanding is wobbly a little here... is'nt that call asynchronous?

Thanks!

**Comment by sebastienricher** [comment]
Also on the readme, I see this code : 

InstaSharpConfig.oauthResponse = oauthResponse.Data;

But oauthResponse does not have a .Data property? (It does have a .Result?)

Am I missing something?

**Comment by theShiva** [comment]
The readme and the current codebase _may be_ out of sync.

**Comment by sebastienricher** [comment]
I also though this morning that I was trying to use this through an MVC web project, is this library more designed to be used in phones?

**Comment by felipepessoto** [comment]
@sebastienricher no, it works fine on Web Projects
