### ISSUE TITLE
How Do I Perform a Tag Search?

### ISSUE THREAD

**Issue by coommark** [burkeholland/InstaSharp#40]
So far, what I have is this:

var config = new InstaSharp.InstagramConfig("blabla", "blabla");
var tags = new InstaSharp.Endpoints.Tags(config);
var result = tags.Search("Obama");

Now what next?

I also tried this:
var tags = new InstaSharp.Endpoints.Tags(config).Search("Obama").Result;

yet nothing comes back... Keeps running forever.

**Comment by felipepessoto** [comment]
You should do

var result = await tags.Search("Cats");

You can see the Test project for examples
