### ISSUE TITLE
How To Perform Unauthenticated Tag Search

### ISSUE THREAD

**Issue by coommark** [burkeholland/InstaSharp#42]
The previous version of Instasharp allowed one to perform search using app credentials only. However the current version does not permit. Is that so?

I try this:

var config = new InstaSharp.InstagramConfig("yadayada",
                "yadayada");
            var search = new InstaSharp.Endpoints.Tags(config);
            var result = search.Search("Cats");

However I am not receiving any response. Please how do I do this? Search for tags?

**Comment by felipepessoto** [comment]
You need to await:

var result = await search.Search("Cats");
