### ISSUE TITLE
next_max_id always null in /users/self/media/liked

### ISSUE THREAD

**Issue by dieterdepuydt** [burkeholland/InstaSharp#54]
When using the "Users" endpoint, the /self/media/liked routine, the property "next_max_id" in "Pagination" is always NULL. That is because the JSON property in that specific routine is called "next_max_like_id".  

I've fixed that quick&dirty for my own project by adding this to the "Pagination" model.

 [JsonProperty("next_max_like_id")]
        public string NextMaxLikeId { get; set; }

**Comment by felipepessoto** [comment]
Please, use the main repo: https://github.com/InstaSharp/InstaSharp/issues
