### ISSUE TITLE
Instasharp.dll couldn't be found

### ISSUE THREAD

**Issue by Tiyyob** [burkeholland/InstaSharp#55]
Hi there,

I downloaded the project and tried to run with Visual Studion 2013. Initially, it gave me the error with NuGet version, i downloaded and installed version 2.8.1 and that error went away.

But after that it gave me following error

Error   4   Metadata file 'F:\Tayyab_Data\Tayyab\Personal\Projects\Instagram\InstaSharp-InstaSharp-2.0.0-9-gaca24bf\InstaSharp-InstaSharp-aca24bf\src\InstaSharp\bin\Debug\InstaSharp.dll' could not be found   F:\Tayyab_Data\Tayyab\Personal\Projects\Instagram\InstaSharp-InstaSharp-2.0.0-9-gaca24bf\InstaSharp-InstaSharp-aca24bf\src\InstaSharp.Tests\CSC InstaSharp.Tests

I tried to add the reference to InstaSharp.dll file by browsing to Bin directory but this directly is empty.

Please advise.

**Comment by theShiva** [comment]
@Tiyyob  Did you download the project from burkeholland / InstaSharp repository? If yes, then this codebase is old i.e. 155 commits behind Instasharp:master

Please download the latest repository from https://github.com/InstaSharp/InstaSharp and try again and let us know.

Thank you!

**Comment by Tiyyob** [comment]
@theShiva , Thank you for your reply, i downloaded the zip file from suggested location but still same situation. Bin directory is empty.

Plus i tried to open both projects (InstaSharp and InstaSharp.Tests) by clicking at the solution file at the main but one project failed to load. Please observe the screen shot attached and advise.
![instasharp_project_load_failed](https://cloud.githubusercontent.com/assets/13675200/9153941/ae165094-3e81-11e5-95d5-7ab6e41aad20.jpg)

**Comment by theShiva** [comment]
@Tiyyob Per your comment on Instasharp/instasharp Gitter, can this issue now be closed?

**Comment by Tiyyob** [comment]
@theShiva , Yes Dear it could be closed now. Your support regarding this issue is truly appreciated. :+1:
